/**
 * What each backend actually EXPOSES of a model's reasoning.
 *
 * Brigade is model-agnostic, so it cannot assume "thinking text" means the same
 * thing everywhere. It does not. Getting this wrong is not cosmetic — labelling
 * a provider-written summary as "the model's thinking" is a factual
 * misrepresentation, and treating an intentionally-empty billed reasoning block
 * as "no thinking happened" hides real cost.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WHAT THE PROVIDERS ACTUALLY DO  (verified against vendor docs, 2026-08)
 * ─────────────────────────────────────────────────────────────────────────
 *
 * ANTHROPIC — summary, never raw. The docs are explicit: "the text in a
 *   thinking block is a summary of Claude's reasoning" and no setting returns
 *   the raw chain of thought; the summary is written by a DIFFERENT model the
 *   reasoning model never sees. Billing does not match what you see: "You're
 *   charged for the full thinking tokens generated by the original request, not
 *   the summary tokens."
 *   `display: "omitted"` is the DEFAULT on the current generation (Opus 5,
 *   Sonnet 5, Fable 5, Opus 4.8, Opus 4.7) — you get `thinking: ""` plus a real
 *   signature, fully billed, and NO `thinking_delta` events at all. That is
 *   `hidden`, not `none`, and the block must still be round-tripped.
 *   https://platform.claude.com/docs/en/build-with-claude/thinking
 *
 * OPENAI — summary for hosted reasoning models (o-series, GPT-5.x): "reasoning
 *   tokens are not visible via the API". The exception is `gpt-oss`, which does
 *   return raw CoT — and OpenAI's own cookbook warns not to show it to users
 *   because it "might contain … instructions in the developer message", i.e. it
 *   can leak the system prompt into the visible pane.
 *   https://developers.openai.com/api/docs/guides/reasoning
 *
 * GOOGLE GEMINI — thought summaries, gated by `includeThoughts`.
 *   https://ai.google.dev/gemini-api/docs/generate-content/thinking
 *
 * XAI GROK — summary: "we expose summarizations of the model's internal
 *   reasoning". https://docs.x.ai/developers/model-capabilities/text/reasoning
 *
 * DEEPSEEK / QWEN / LOCAL WEIGHTS — a `reasoning_content` field documented as
 *   the model's chain of thought, not described as a summary. Treated as `raw`.
 *   https://api-docs.deepseek.com/guides/thinking_mode/
 *
 * OLLAMA — parses the model's thinking into a structured `thinking` field and
 *   streams it before the answer; local weights, so raw.
 *   https://docs.ollama.com/capabilities/thinking
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WHY A STATIC MAP IS NOT ENOUGH
 * ─────────────────────────────────────────────────────────────────────────
 * The static map is a starting guess from the provider id. The RUNTIME refiner
 * below is what makes it honest, because two states are only observable from
 * the stream itself: a block that arrives with a signature and no text
 * (`hidden` — billed, omitted by policy), and a block the safety filter
 * redacted (`redacted`). Neither is predictable from the model id.
 */

import type { ReasoningVisibility } from "../../protocol.js";

/** Providers whose reasoning output is a summary, never the raw chain of thought. */
const SUMMARY_PROVIDERS = new Set([
	"anthropic",
	"claude-cli",
	"claude-code",
	"amazon-bedrock",
	"bedrock",
	"google-vertex",
	"vertex",
	"google",
	"gemini",
	"openai",
	"openai-codex",
	"azure-openai",
	"xai",
	"github-copilot",
]);

/** Providers that hand back something documented as the model's own reasoning. */
const RAW_PROVIDERS = new Set([
	"deepseek",
	"deepseek-sub",
	"qwen",
	"ollama",
	"ollama-native",
	"groq",
	"cerebras",
	"minimax-sub",
	"glm",
	"kimi",
	"nvidia-nim",
	"mistral",
]);

/**
 * Best initial guess for a backend, before any reasoning has streamed.
 *
 * Defaults to `summary` for an UNKNOWN provider rather than `raw`. That is the
 * conservative choice: understating fidelity is a smaller error than telling
 * the operator they are reading the model's actual chain of thought when they
 * are reading a paraphrase.
 */
export function initialReasoningVisibility(input: {
	provider: string | undefined;
	modelId?: string | undefined;
}): ReasoningVisibility {
	const provider = (input.provider ?? "").trim().toLowerCase();
	const modelId = (input.modelId ?? "").trim().toLowerCase();

	// `gpt-oss` is the one OpenAI family that returns raw CoT, on whatever
	// provider is serving it (OpenAI, Groq, Ollama, a local shim).
	if (modelId.includes("gpt-oss")) return "raw";

	if (RAW_PROVIDERS.has(provider)) return "raw";
	if (SUMMARY_PROVIDERS.has(provider)) return "summary";
	return "summary";
}

/**
 * Refine visibility from an actual thinking block, which is the only way to
 * observe the two states a model id cannot predict.
 *
 *   - `redacted: true`      the safety filter removed it. Opaque payload only.
 *   - empty text + signature the provider omitted it BY POLICY (Anthropic's
 *                            `display:"omitted"`, the current default). It is
 *                            billed and required for round-trip, so it must
 *                            never be reported as "no reasoning".
 *
 * Returns the refined value, or `current` when the block tells us nothing new.
 * Never widens fidelity — a block can prove reasoning is hidden or redacted,
 * but it can never prove a summary was actually raw.
 */
export function refineReasoningVisibility(
	current: ReasoningVisibility,
	block: { thinking?: string; thinkingSignature?: string; redacted?: boolean } | undefined,
): ReasoningVisibility {
	if (!block) return current;
	if (block.redacted === true) return "redacted";
	const hasText = typeof block.thinking === "string" && block.thinking.trim().length > 0;
	const hasSignature = typeof block.thinkingSignature === "string" && block.thinkingSignature.length > 0;
	if (!hasText && hasSignature) return "hidden";
	return current;
}

/**
 * How a UI should label this reasoning, in the operator's words.
 *
 * Deliberately not "thinking" for the summary case: on most providers the
 * operator is reading a paraphrase produced by a different model, and calling
 * that the model's thinking is a misrepresentation.
 */
export function describeReasoningVisibility(v: ReasoningVisibility): string {
	switch (v) {
		case "raw":
			return "the model's reasoning";
		case "summary":
			return "a summary of the model's reasoning";
		case "redacted":
			return "reasoning redacted by the provider";
		case "hidden":
			return "reasoning hidden by the provider (still billed)";
		case "none":
			return "this model does not reason";
	}
}

/** Whether a renderer may show reasoning TEXT at all for this visibility. */
export function hasReadableReasoning(v: ReasoningVisibility): boolean {
	return v === "raw" || v === "summary";
}
